behaviors:
  SliderAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 512
      learning_rate: 0.0003
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 32
    summary_freq: 10000
